### ISSUE TITLE
[ERROR] - [RPM] - [v 0.3.0-1] - Error during install / Package conflicts

### ISSUE THREAD

**Issue by btex88** [alt-art/commit#2]
While installing ```commit``` I've encountered an error that wasn't able to be resolved by ```dnf``` package manager.

The distro I'm using is ***Fedora 35*** (XFCE official version) the version of the that I'm trying to install ```commit``` that I'm trying to install  is ```v 0.3.0-1```.

The error it self was:
```
Error: Transaction test error:
  file /usr/bin from install of commit-0:0.3.0-1.x86_64 conflicts with file from package filesystem-3.14-7.fc35.x86_64
```

__BTW - This app is f****ing amazing!!!__

**Comment by alt-art** [comment]
Thanks for the report, I am working on this now.

**Comment by alt-art** [comment]
Release 0.3.1 will fix this error.
