### ISSUE TITLE
Search in parent folders for commit.json config file

### ISSUE THREAD

**Issue by alt-art** [alt-art/commit#42]
The current implementation only searches the config file in pwd, home folder and argument, But git and other tools as the capability of searching config files and folders in parent folders in case someone move out of the config file folder.

Note: This will need a depth value for stop at a given iteration

Function that will handle this: https://github.com/alt-art/commit/blob/ac7cfe0dd085d559c91864285fd62f705033ab5c/src/config/mod.rs#L81-L92

**Comment by letsaguiar** [comment]
Hey, I really appreciate this project :D I'm excited to work on this issue :D

**Comment by alt-art** [comment]
You can bother me if you have any question or if you need help.

**Comment by PrathameshTheurkar** [comment]
hey @alt-art can you assign this issue to me plz . I would love to contribute to this issue .
